[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/send-email"
  to = "/.netlify/functions/send-email"
  status = 200

[[redirects]]
  from = "/api/test-email-connection"
  to = "/.netlify/functions/test-connection"
  status = 200